-- ============================================================
-- Migration: Supabase Storage Bucket for LPA PDFs
-- ============================================================

insert into storage.buckets (id, name, public, file_size_limit)
values ('lpa-pdfs', 'lpa-pdfs', false, 10485760);  -- 10MB limit

-- Storage RLS: Only allow Edge Functions (service_role) to upload/manage files
-- Leads can read their own PDFs via signed URLs generated by Edge Functions

-- Allow authenticated users to read their own application PDFs
create policy storage_lpa_pdfs_select on storage.objects
  for select using (
    bucket_id = 'lpa-pdfs'
    and (
      -- Admin can read all
      public.is_admin()
      or
      -- Lead can read their own application's PDFs
      -- Path structure: {application_id}/{lpa_document_id}/{lpa_type}.pdf
      exists (
        select 1 from public.applications a
        where a.id::text = (storage.foldername(name))[1]
          and a.lead_id = auth.uid()
      )
    )
  );
